### ISSUE TITLE
Реализовать кнопку карточки в соответствии с макетом

### ISSUE THREAD

**Issue by Baga9898** [fghtd/first-template#4]
https://github.com/fghtd/first-template/blob/bf75a6be74af5922dd4ed0c70c7ebb8110f502b8/index.html#L65

Если у класса `description` убрать цвет - станет явно видно что стили рамок не соответствуют макету:

![image](https://github.com/fghtd/first-template/assets/61385284/619e7bc1-d3e9-44b5-bf9b-f30b18c95994)

Это можно пофиксить посредством удаления свойства `border-color` и его замены на `border` в последствии.
Свойство `border` имеет три параметра:

```
border: [[border-width](https://htmlbook.ru/css/border-width) || [border-style](https://htmlbook.ru/css/border-style) || [border-color](https://htmlbook.ru/css/border-color)] | inherit
```

Соответственно, необходимо явно задать желаемый вариант значения свойства `border-style`:

```
.description {
  padding: 20.5px 59px;
  background: transparent;
  border: 1px solid #bae249;
  font-size: 16px;
  line-height: 150%;
  color: #bae249;
}
```

![image](https://github.com/fghtd/first-template/assets/61385284/189b03a9-308f-4a2e-abfd-bcd2e4d7dc08)

Отлично, эта проблема решена, но теперь обнаружена новая проблема с размерами кнопки, они не высчитываются динамически, необходимо это исправить:

.description {
  width: 150px;
  height: 45px;
  border: 1px solid #bae249;
  background: transparent;
  font-size: 16px;
  color: #bae249;
}

![image](https://github.com/fghtd/first-template/assets/61385284/8ee2e6cb-27bd-4293-be2b-5263dc7f9282)

**Comment by fghtd** [comment]
Сделаль.
